package Simple;

import Main.Entry;
import static Main.Entry.simpCalc;
import Old.Processor;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 * Provides SimpCalc GUI
 *
 * @author David
 */
public class SimpCalc extends javax.swing.JFrame {

    // Program version string
    private static final String VERSION = "1.0";

    /**
     * Creates GUI
     */
    public SimpCalc() {
        initComponents();
    }

    /**
     * Make adjustments to an initialized SimpCalc frame
     */
    public static void adjustFrame() {
        // Make adjustments to frame
        Entry.simpCalc.setVisible(true);
        Entry.simpCalc.setTitle("SimpCalc V" + VERSION + " - by David C, 2019");
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int frameXPos = ((int) screen.getWidth() / 2) - (simpCalc.getWidth() / 2);
        Entry.simpCalc.setLocation(frameXPos, 39);
        Entry.simpCalc.setResizable(false);
        Entry.simpCalc.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JMenuBar jMenuBar2 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar3 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu5 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar4 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu6 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu7 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar5 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu8 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu9 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar6 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu10 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu11 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JMenuBar jMenuBar7 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu12 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu13 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar8 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu14 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu15 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar9 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu16 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu17 = new javax.swing.JMenu();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel title = new javax.swing.JLabel();
        javax.swing.JTextField num2 = new javax.swing.JTextField();
        javax.swing.JTextField num1 = new javax.swing.JTextField();
        javax.swing.JLabel result = new javax.swing.JLabel();
        javax.swing.JButton subOp = new javax.swing.JButton();
        javax.swing.JButton addOp = new javax.swing.JButton();
        javax.swing.JButton powOp = new javax.swing.JButton();
        javax.swing.JButton divOp = new javax.swing.JButton();
        javax.swing.JButton mulOp = new javax.swing.JButton();
        javax.swing.JButton tryOther = new javax.swing.JButton();
        javax.swing.JButton modOp = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar3.add(jMenu2);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar6.add(jMenu11);

        jMenuItem5.setText("jMenuItem5");

        jMenu12.setText("File");
        jMenuBar7.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar8.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar8.add(jMenu15);

        jMenu16.setText("File");
        jMenuBar9.add(jMenu16);

        jMenu17.setText("Edit");
        jMenuBar9.add(jMenu17);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        panel.setBackground(new java.awt.Color(153, 204, 255));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setName("panel"); // NOI18N

        title.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SimpCalc");
        title.setName("title"); // NOI18N

        num2.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        num2.setText("Second Number");
        num2.setName("num2"); // NOI18N
        num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearOnClick(evt);
            }
        });
        num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actOnEnter(evt);
            }
        });

        num1.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        num1.setText("First Number");
        num1.setName("num1"); // NOI18N
        num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearOnClick(evt);
            }
        });
        num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actOnEnter(evt);
            }
        });

        result.setBackground(new java.awt.Color(0, 0, 0));
        result.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        result.setForeground(new java.awt.Color(0, 0, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText("Result");
        result.setName("result"); // NOI18N

        subOp.setBackground(new java.awt.Color(51, 102, 255));
        subOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        subOp.setForeground(new java.awt.Color(0, 0, 0));
        subOp.setText("-");
        subOp.setToolTipText("");
        subOp.setAlignmentY(0.0F);
        subOp.setBorder(null);
        subOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subOp.setIconTextGap(0);
        subOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        subOp.setName("startBut"); // NOI18N
        subOp.setPreferredSize(new java.awt.Dimension(75, 75));
        subOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subOpActionPerformed(evt);
            }
        });

        addOp.setBackground(new java.awt.Color(51, 102, 255));
        addOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addOp.setForeground(new java.awt.Color(0, 0, 0));
        addOp.setText("+");
        addOp.setToolTipText("");
        addOp.setAlignmentY(0.0F);
        addOp.setBorder(null);
        addOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOp.setIconTextGap(0);
        addOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addOp.setName("startBut"); // NOI18N
        addOp.setPreferredSize(new java.awt.Dimension(75, 75));
        addOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOpActionPerformed(evt);
            }
        });

        powOp.setBackground(new java.awt.Color(51, 102, 255));
        powOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        powOp.setForeground(new java.awt.Color(0, 0, 0));
        powOp.setText("^");
        powOp.setToolTipText("");
        powOp.setAlignmentY(0.0F);
        powOp.setBorder(null);
        powOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        powOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        powOp.setIconTextGap(0);
        powOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        powOp.setName("powOp"); // NOI18N
        powOp.setPreferredSize(new java.awt.Dimension(75, 75));
        powOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powOpActionPerformed(evt);
            }
        });

        divOp.setBackground(new java.awt.Color(51, 102, 255));
        divOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        divOp.setForeground(new java.awt.Color(0, 0, 0));
        divOp.setText("\u00F7");
        divOp.setToolTipText("");
        divOp.setAlignmentY(0.0F);
        divOp.setBorder(null);
        divOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        divOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divOp.setIconTextGap(0);
        divOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        divOp.setName("startBut"); // NOI18N
        divOp.setPreferredSize(new java.awt.Dimension(75, 75));
        divOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divOpActionPerformed(evt);
            }
        });

        mulOp.setBackground(new java.awt.Color(51, 102, 255));
        mulOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mulOp.setForeground(new java.awt.Color(0, 0, 0));
        mulOp.setText("x");
        mulOp.setToolTipText("");
        mulOp.setAlignmentY(0.0F);
        mulOp.setBorder(null);
        mulOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mulOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mulOp.setIconTextGap(0);
        mulOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mulOp.setName("startBut"); // NOI18N
        mulOp.setPreferredSize(new java.awt.Dimension(75, 75));
        mulOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulOpActionPerformed(evt);
            }
        });

        tryOther.setBackground(new java.awt.Color(255, 255, 153));
        tryOther.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tryOther.setForeground(new java.awt.Color(0, 0, 0));
        tryOther.setText("Try Other");
        tryOther.setToolTipText("");
        tryOther.setAlignmentY(0.0F);
        tryOther.setBorder(null);
        tryOther.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tryOther.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tryOther.setIconTextGap(0);
        tryOther.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tryOther.setName("startBut"); // NOI18N
        tryOther.setPreferredSize(new java.awt.Dimension(75, 75));
        tryOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryOtherActionPerformed(evt);
            }
        });

        modOp.setBackground(new java.awt.Color(51, 102, 255));
        modOp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        modOp.setForeground(new java.awt.Color(0, 0, 0));
        modOp.setText("%");
        modOp.setToolTipText("");
        modOp.setAlignmentY(0.0F);
        modOp.setBorder(null);
        modOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modOp.setIconTextGap(0);
        modOp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        modOp.setName("startBut"); // NOI18N
        modOp.setPreferredSize(new java.awt.Dimension(75, 75));
        modOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modOpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(powOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(mulOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(divOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(num1))
                        .addGap(50, 50, 50)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(addOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(subOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(modOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(num2))))
                .addGap(77, 77, 77))
            .addComponent(tryOther, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(tryOther, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modOp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jMenuBar1.setBorder(null);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subOpActionPerformed
        calculate('-');
    }//GEN-LAST:event_subOpActionPerformed

    private void addOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOpActionPerformed
        calculate('+');
    }//GEN-LAST:event_addOpActionPerformed

    private void powOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powOpActionPerformed
        calculate('^');
    }//GEN-LAST:event_powOpActionPerformed

    private void divOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divOpActionPerformed
        calculate('/');
    }//GEN-LAST:event_divOpActionPerformed

    private void mulOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulOpActionPerformed
        calculate('*');
    }//GEN-LAST:event_mulOpActionPerformed

    private void modOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modOpActionPerformed
        calculate('%');
    }
	//GEN-LAST:event_modOpActionPerformed

    /**
     * Process the two inputted numbers with a given operator
     *
     * @param op
     */
    private void calculate(char op) {

        try {
            // Get input
            String firstS = ((JTextField) getComponentByName("num1")).getText();
            double first = Double.parseDouble(firstS);
            String secondS = ((JTextField) getComponentByName("num2")).getText();
            double second = Double.parseDouble(secondS);

            // Compute with processor
            Processor proc = new Processor();
            String result = proc.evaluateArgs(first, second, op);
            ((JLabel) getComponentByName("result")).setText(result);

        } catch (NumberFormatException e) {

            // If any errors occur, result is 'Error'
            ((JLabel) getComponentByName("result")).setText("Error");

        }
    }

    /**
     * Clear the JTextFields when they are clicked
     * @param evt 
     */
    private void clearOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearOnClick

        // Clear field
        ((JTextField) evt.getSource()).setText("");
    }//GEN-LAST:event_clearOnClick


    /**
     * Switch to other calculator when 'Try Other' is pressed
     * @param evt 
     */
    private void tryOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryOtherActionPerformed

        Entry.switchToOld();
    }//GEN-LAST:event_tryOtherActionPerformed

    /**
     * When enter is pressed, move to next field
     * @param evt 
     */
    private void actOnEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actOnEnter

        // If enter is pressed
        if (evt.getKeyCode() == 10) {

            // Get name of field pressed
            String curName = ((JTextField) evt.getComponent()).getName();

            // If currently focused on num1
            if (curName.equals("num1")) {

                // Clear num2 
                ((JTextField) getComponentByName("num2")).setText("");

                // Move focus to num2
                ((JTextField) getComponentByName("num2")).requestFocus();
            }
            else
            {
                // If on num2, go to next operator
                ((JButton) getComponentByName("powOp")).requestFocus();
            }
        }
    }//GEN-LAST:event_actOnEnter

    /**
     * Retrieve a SimpCalc component by its name
     *
     * @param nameQuery
     * @return
     */
    public Component getComponentByName(String nameQuery) {
        // Return variable
        Component comp = null;

        // Get all components
        JRootPane jrp = (JRootPane) Entry.simpCalc.getComponents()[0];
        Container cp = (Container) jrp.getContentPane();
        JPanel jp = (JPanel) cp.getComponents()[0];
        Component[] parts = jp.getComponents();

        // Iterate over all parts
        for (Component curComp : parts) {
            // When name matches, save and stop
            if (nameQuery.equalsIgnoreCase(curComp.getName())) {
                comp = curComp;
                break;
            }
        }

        // Return component
        return comp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
